FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /source

COPY . .

RUN dotnet tool install dotnet-reportgenerator-globaltool --tool-path /tools

CMD dotnet test --collect:"XPlat Code Coverage" && \
    /tools/reportgenerator \
        -reports:"/source/Tests/**/coverage.cobertura.xml" \
        -targetdir:"coveragereport" \
        -reporttypes:Html