FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /sln

COPY . .

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN dotnet build *.sln && \
   dotnet pack nuget.csproj \
      # --no-build \
      --configuration Release \
      --output artifacts 

#if (pipeline=="gitlab")
ARG CI_REGISTRY_USER=''
ARG CI_JOB_TOKEN=''
ARG CI_REGISTRY_URL=''

RUN dotnet nuget add source $CI_REGISTRY_URL \
   --name gitlab \
   --username $CI_REGISTRY_USER \
   --password $CI_JOB_TOKEN \
   --store-password-in-clear-text
#endif

ENTRYPOINT [ "dotnet", "nuget", "push", "artifacts/*.nupkg", "--skip-duplicate" ]
CMD [ "--source", "https://api.nuget.org/v3/index.json" ]