FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /sln

COPY . .

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

ARG Version

RUN dotnet pack \
   --configuration Release \
   --output artifacts \
   /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg \
   /p:Version=$Version

ENTRYPOINT [ "dotnet", "nuget", "push", "artifacts/*.nupkg", "--skip-duplicate" ]
CMD [ "--source", "https://api.nuget.org/v3/index.json" ]