name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pack dependencies
      run: docker build -t pack --buil-arg Version=1.0.0
    - name: Publish
      run: docker run pack --api-key $NUGETAPIKEY --source https://api.nuget.org/v3/index.json
